import type { UserData, Menu, Profile, LifeRecord } from "./types";
export const dateISO = (date = new Date()) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
export let today = dateISO();
export function refreshToday() {
  const next = dateISO();
  const changed = next !== today;
  today = next;
  return changed;
}
export const profiles: Profile[] = [
  {
    id: "demo-lin",
    studentId: "0020240101",
    name: "林同学",
    grade: "2024",
    major: "交通运输",
    gender: "不愿透露",
  },
  {
    id: "demo-chen",
    studentId: "0020250202",
    name: "陈同学",
    grade: "2025",
    major: "计算机科学与技术",
    gender: "不愿透露",
  },
];
export const menus: Menu[] = [
  {
    id: "b1",
    meal: "早餐",
    food: "小米粥 · 鸡蛋 · 玉米",
    place: "中心食堂",
    cost: 8,
    kcal: 380,
    protein: 17,
    taste: "清淡",
    minutes: 15,
    ingredients: "小米 鸡蛋 玉米",
  },
  {
    id: "b2",
    meal: "早餐",
    food: "豆浆 · 素菜包",
    place: "第五食堂",
    cost: 7,
    kcal: 350,
    protein: 13,
    taste: "清淡",
    minutes: 12,
    ingredients: "大豆 小麦 青菜",
  },
  {
    id: "b3",
    meal: "早餐",
    food: "鸡蛋煎饼 · 热牛奶",
    place: "方舟美食广场",
    cost: 12,
    kcal: 490,
    protein: 22,
    taste: "家常",
    minutes: 10,
    ingredients: "鸡蛋 小麦 牛奶",
  },
  {
    id: "b4",
    meal: "早餐",
    food: "燕麦 · 香蕉 · 酸奶",
    place: "心海餐厅",
    cost: 13,
    kcal: 410,
    protein: 16,
    taste: "清淡",
    minutes: 10,
    ingredients: "燕麦 香蕉 牛奶",
  },
  {
    id: "l1",
    meal: "午餐",
    food: "香菇鸡肉饭 · 时蔬",
    place: "中心食堂",
    cost: 16,
    kcal: 610,
    protein: 32,
    taste: "家常",
    minutes: 25,
    ingredients: "鸡肉 香菇 米饭 青菜",
  },
  {
    id: "l2",
    meal: "午餐",
    food: "番茄鸡蛋面",
    place: "第五食堂",
    cost: 12,
    kcal: 520,
    protein: 19,
    taste: "清淡",
    minutes: 20,
    ingredients: "番茄 鸡蛋 小麦",
  },
  {
    id: "l3",
    meal: "午餐",
    food: "香辣牛肉饭",
    place: "方舟美食广场",
    cost: 22,
    kcal: 680,
    protein: 35,
    taste: "香辣",
    minutes: 25,
    ingredients: "牛肉 米饭 辣椒",
  },
  {
    id: "l4",
    meal: "午餐",
    food: "清蒸鱼 · 杂粮饭",
    place: "心海餐厅",
    cost: 20,
    kcal: 560,
    protein: 36,
    taste: "清淡",
    minutes: 30,
    ingredients: "鱼 大米 玉米",
  },
  {
    id: "d1",
    meal: "晚餐",
    food: "山药排骨汤 · 米饭",
    place: "中心食堂",
    cost: 18,
    kcal: 540,
    protein: 26,
    taste: "清淡",
    minutes: 25,
    ingredients: "山药 猪肉 大米",
  },
  {
    id: "d2",
    meal: "晚餐",
    food: "菌菇豆腐 · 杂粮饭",
    place: "第五食堂",
    cost: 13,
    kcal: 460,
    protein: 20,
    taste: "清淡",
    minutes: 20,
    ingredients: "菌菇 大豆 大米",
  },
  {
    id: "d3",
    meal: "晚餐",
    food: "麻辣香锅 · 米饭",
    place: "方舟美食广场",
    cost: 23,
    kcal: 720,
    protein: 24,
    taste: "香辣",
    minutes: 30,
    ingredients: "鸡肉 豆腐 花生 辣椒",
  },
  {
    id: "d4",
    meal: "晚餐",
    food: "时蔬鸡肉面",
    place: "心海餐厅",
    cost: 15,
    kcal: 490,
    protein: 28,
    taste: "家常",
    minutes: 20,
    ingredients: "鸡肉 小麦 青菜",
  },
];
export function seedData(userId: string): UserData {
  const shift = userId === "demo-chen";
  const weekday = new Date().getDay() || 7;
  const records: LifeRecord[] = [
    {
      id: "course-1",
      kind: "course",
      date: today,
      title: shift ? "高等数学" : "交通运输概论",
      weekday,
      start: "08:30",
      end: "10:05",
      place: "学汇楼",
      teacher: "王老师",
      weeks: "1-20",
      source: "示例",
    },
    {
      id: "course-2",
      kind: "course",
      date: today,
      title: shift ? "大学英语" : "概率论与数理统计",
      weekday,
      start: "10:25",
      end: "12:00",
      place: "百川楼",
      teacher: "李老师",
      weeks: "1-20",
      source: "示例",
    },
    {
      id: "task-1",
      kind: "task",
      date: today,
      title: "去图书馆，读完那本书",
      start: "14:00",
      duration: 60,
      place: "图书馆",
      done: false,
      source: "示例",
    },
    {
      id: "meal-1",
      kind: "meal",
      date: today,
      title: "小米粥 · 鸡蛋 · 玉米",
      meal: "早餐",
      portion: "1 份",
      cost: 8,
      kcal: 380,
      protein: 17,
      place: "中心食堂",
      planned: false,
      source: "示例",
    },
    {
      id: "meal-2",
      kind: "meal",
      date: today,
      title: "香菇鸡肉饭 · 时蔬",
      meal: "午餐",
      start: "12:10",
      duration: 25,
      cost: 16,
      kcal: 610,
      protein: 32,
      place: "中心食堂",
      planned: true,
      source: "示例",
    },
  ];
  for (let i = 0; i < 7; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const date = dateISO(d);
    const prev = new Date(d);
    prev.setDate(d.getDate() - 1);
    records.push(
      {
        id: `sleep-${i}`,
        kind: "sleep",
        date,
        title: "昨夜睡眠",
        sleepStart: dateISO(prev) + "T23:20",
        sleepEnd: date + "T07:10",
        quality: 4,
        source: "示例",
      },
      {
        id: `exercise-${i}`,
        kind: "exercise",
        date,
        title: "校园散步",
        mode: "步行",
        duration: 25 + i * 3,
        distance: 1.5 + i * 0.2,
        steps: (shift ? 3800 : 5200) + i * 230,
        source: "示例",
      },
      {
        id: `mood-${i}`,
        kind: "mood",
        date,
        title: "今天的心情",
        mood: 4,
        stress: 2 + (i % 2),
        note: "慢慢来，也是在向前走。",
        source: "示例",
      },
    );
  }
  const monday = new Date();
  monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7) - 14);
  return {
    records,
    awards: [],
    messages: [],
    preferences: {
      healthGoal: "保持健康",
      healthWeight: 0.4,
      timeWeight: 0.4,
      costWeight: 0.2,
      modes: ["步行"],
      taste: "不限",
      avoid: "",
      budget: 25,
      lead: 10,
      termStart: dateISO(monday),
      learningRate: 0.01,
      exploration: 0.1,
      lstm: 64,
      dropout: 0.2,
    },
  };
}
